// <auto-generated />
using Course.App.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Course.App.Migrations.Migrations
{
    [DbContext(typeof(TrainingSubscriptionDbContext))]
    [Migration("20230723161339_PopulateDb")]
    partial class PopulateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Course.App.DataModel.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CCode = "C101",
                            Description = "C# Advanced programming",
                            Name = ".Net Web API",
                            Status = "Active",
                            Title = "C# Net Web API & EF"
                        },
                        new
                        {
                            Id = 2,
                            CCode = "C102",
                            Description = "ASP.net MVC from scratch",
                            Name = "ASP.net core",
                            Status = "Active",
                            Title = "Build an app with ASPNET MVC"
                        },
                        new
                        {
                            Id = 3,
                            CCode = "C103",
                            Description = "Angular Fundamental step by step",
                            Name = "Angular 10",
                            Status = "Active",
                            Title = "Angular Fundamental"
                        },
                        new
                        {
                            Id = 4,
                            CCode = "C104",
                            Description = "PHP for beginner",
                            Name = "PHP for beginner",
                            Status = "Hold",
                            Title = "PHP for beginner"
                        });
                });

            modelBuilder.Entity("Course.App.DataModel.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("Course.App.DataModel.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Training", (string)null);
                });

            modelBuilder.Entity("Course.App.DataModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 3850050L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3850058,
                            Email = "rajan_adiga@terry.test",
                            Gender = "female",
                            Name = "Rajan Adiga",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3850059,
                            Email = "draupadi_khanna@torphy.test",
                            Gender = "male",
                            Name = "Draupadi Khanna",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 3850060,
                            Email = "ganaka_sen_mehrotra@hodkiewicz.example",
                            Gender = "male",
                            Name = "Sen. Ganaka Mehrotra",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 3850061,
                            Email = "trivedi_harinarayan@koss.example",
                            Gender = "male",
                            Name = "Harinarayan Trivedi",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 3850062,
                            Email = "panicker_rahul_do@emard.example",
                            Gender = "female",
                            Name = "Rahul Panicker DO",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3850063,
                            Email = "dutta_ujjawal@crooks.example",
                            Gender = "male",
                            Name = "Ujjawal Dutta",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 3850064,
                            Email = "sethi_himadri_ii@kihn-gusikowski.test",
                            Gender = "male",
                            Name = "Himadri Sethi II",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3850065,
                            Email = "vaishno_mrs_pillai@aufderhar.test",
                            Gender = "male",
                            Name = "Mrs. Vaishno Pillai",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 3850066,
                            Email = "gandhi_bhavani@hane.test",
                            Gender = "female",
                            Name = "Bhavani Gandhi",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 3850068,
                            Email = "leela_embranthiri@feest.example",
                            Gender = "female",
                            Name = "Leela Embranthiri",
                            Status = "active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
